channels:
  - name: "radar_peterburg"
    username: "radar_peterburg"
    enabled: true
    rules:
      - "kirishi_alert"
    targets:
      - "home_alisa"
  - name: "Тревога"
    username: "thsbshsge"
    enabled: true
    rules:
      - "kirishi_alert"
    targets:
      - "home_alisa"