channels:
  - name: "radar_peterburg"
    username: "radar_peterburg"
    enabled: true
    trigger_scenario: true

    important_geo:
      - "кириши"
      - "киришский район"

    trigger_phrases:
      - "фиксации бпла"
      - "фиксация бпла"
      - "опасность по бпла"

    exclude_phrases:
      - "отбой"
      - "отбой опасности"
      - "фиксаций не наблюдаем"
      - "не наблюдаем"
      - "по обстановке тихо"
      - "тихо"
      - "мониторим обстановку"
      - "в случае возникновения угрозы"
      - "возможно понижение скорости мобильного интернета"
      - "уничтожено"
      - "уничтожен"
      - "уничтожены"
      - "сбито"
      - "сбитие бпла"
      - "локализовано"
      - "обломки"
      - "повреждено"
      - "повредили"
      - "последствия устранены"
      - "пострадавших"
      - "пострадавшим оказывается помощь"
      - "возгорание"
      - "идет отражение атаки"
      - "отражение атаки продолжается"
      - "продолжается работа пво"

    ignore_lines:
      - "❗️Радар Питер и Ленинградская область - @radar_peterburg"
  - name: "thsbshsgeлдлдлдл"
    username: "thsbshsge"
    enabled: true
    trigger_scenario: true

    important_geo:
      - "кириши"
      - "киришский район"

    trigger_phrases:
      - "фиксации бпла"
      - "фиксация бпла"
      - "опасность по бпла"

    exclude_phrases:
      - "отбой"
      - "отбой опасности"
      - "фиксаций не наблюдаем"
      - "не наблюдаем"
      - "по обстановке тихо"
      - "тихо"
      - "мониторим обстановку"
      - "в случае возникновения угрозы"
      - "возможно понижение скорости мобильного интернета"
      - "уничтожено"
      - "уничтожен"
      - "уничтожены"
      - "сбито"
      - "сбитие бпла"
      - "локализовано"
      - "обломки"
      - "повреждено"
      - "повредили"
      - "последствия устранены"
      - "пострадавших"
      - "пострадавшим оказывается помощь"
      - "возгорание"
      - "идет отражение атаки"
      - "отражение атаки продолжается"
      - "продолжается работа пво"

    ignore_lines:
      - "❗️Радар Питер и Ленинградская область - @radar_peterburg"