targets:
  - name: "home_alisa"
    type: "yandex_scenario"
    enabled: true
    scenario_env: "YANDEX_SCENARIO_ID"

  - name: "parents_alisa"
    type: "yandex_scenario"
    enabled: false
    scenario_env: "YANDEX_PARENTS_SCENARIO_ID"
